apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends-staging
  name: techtrends-staging
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: techtrends-staging
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends-staging
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: techtrends-staging
        ports:
        - containerPort:  {{ .Values.containerPort }}
        resources:
         limits:
          cpu: {{ .Values.resources.limits.cpu }}
          memory: {{ .Values.resources.limits.memory }}
         requests:
          cpu: {{ .Values.resources.requests.cpu }}
          memory: {{ .Values.resources.requests.memory }}
        livenessProbe:
         httpGet:
          path: {{ .Values.livenessProbe.httpGet.path }}
          port: {{ .Values.livenessProbe.httpGet.port }}
        readinessProbe:
         httpGet:
          path: {{ .Values.readinessProbe.httpGet.path }}
          port: {{ .Values.readinessProbe.httpGet.port }}



