apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  destination:
    namespace: {{ .Values.namespace.name }}
    server: https://kubernetes.default.svc
  project: {{ .Values.namespace.name }}
  source:
    helm:
      valueFiles:
      - values-staging.yaml
    path: project/argocd
    repoURL: https://github.com/goldencloudcity/nd064_course_1 
    targetRevision: HEAD
